### ISSUE TITLE
Thank your for deleting by default my migrations

### ISSUE THREAD

**Issue by jbeyer1984** [NoelDeMartin/laravel-cypress#2]
Hello, thank you for this package.

In respect to you I can say it is a really clean solution you've programmed.
But I'd trouble with identifying which/what has cleaned my tables.
It was not that hard for me, but it cost time.

So when you do something like Artisan::call('migrate:fresh');.
First you should NOTE it in the readme.
Or offer configuration for this issue.

Best regards
Jens Beyer

**Comment by NoelDeMartin** [comment]
Hello Jens, thanks for opening the issue.

You're right that I should provide some configuration, I'll keep this issue open until I do.

But note that it isn't uncommon to run migrations in tests, and there is already [protection](https://github.com/NoelDeMartin/laravel-cypress/blob/master/src/CypressServiceProvider.php#L39) so that this isn't run in production. Each test must start with a clean environment, that's why the migrations are run. You can see [some examples](https://laravel.com/docs/7.x/dusk#creating-browsers) in the official Laravel Dusk documentation where they do the same.

**Comment by NoelDeMartin** [comment]
I've released new versions for both laravel-cypress and [cypress-laravel](https://github.com/NoelDeMartin/cypress-laravel).

After you update the packages, you'll need to call `useDatabaseMigrations` if you want to have migrations running.
